verbose_debug = false
state_finder_debug = false
re_apply_movement = false
debug_view = false
debug_view_fps = 15
advanced_debug_visuals = false
record_debug_preview_clips = false
match_frame_sampling = true
match_frame_interval = 1.5
match_frame_max = 300
